# Generated by Django 5.0 on 2024-01-02 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploy',
            old_name='name_of_webistes',
            new_name='name_of_websites',
        ),
    ]
